GRANT REPLICATION SLAVE, REPLICATION CLIENT, RELOAD, LOCK TABLES ON *.* TO 'test'@'%';
FLUSH PRIVILEGES;

CREATE TABLE user_model (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO user_model(id, name) VALUES (1, 'alice');
